trigger:
  branches:
    include:
      - main

variables:
  # Variables de entorno
  ACR_NAME: 'devopsapp' 
  IMAGE_NAME: 'appdevops-image-grupo2'
  SERVICE_CONNECTION_NAME: 'appdevops-grupo2'

jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build and Push Docker Image'
